### ISSUE TITLE
Error with Glimmer 2 [Ember 2.9.0 bata 3]

### ISSUE THREAD

**Issue by josemarluedke** [plusacht/ember-bootstrap-datetimepicker#86] opened 2016-09-26 23:53 UTC
Hey there! 

We are getting an error when using this addon with Ember 2.9.0 beta 3 where Glimmer 2 is the new rendering engine.

```
// bootstrap-datetimepicker.js:2254

Uncaught TypeError: input.size is not a function
```

The stack trace points to this block:

```
            input = element.find(options.datepickerInput);
            if (input.size() === 0) {
                input = element.find('input');
            } else if (!input.is('input')) {
                throw new Error('CSS class "' + options.datepickerInput + '" cannot be applied to non input element');
            }
```

Would be wonderful if you could take a look on this. Thanks.

**Comment by josemarluedke** [comment] 2016-09-30 23:07
This is also happening in Ember 2.8.1.

**Comment by miguelcobain** [comment] 2016-10-11 10:17
The problem is that the `size` function was removed in jquery 3.0

**Comment by josemarluedke** [comment] 2016-10-15 02:34
It seems that this is a problem in upstream related to jquery version. More info: https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1684

**Comment by pcambra** [comment] 2016-11-25 03:25
Confirmed that updating the ember-bootstrap-datetimepicker version to 4.17.42 in the package.json file fixes the issue

**Comment by jasonmit** [comment] 2017-01-02 01:50
Should be fixed on master, https://github.com/plusacht/ember-bootstrap-datetimepicker/blob/master/blueprints/ember-bootstrap-datetimepicker/index.js#L6

**Closed by jasonmit** 2017-01-02 01:50 UTC
