### ISSUE TITLE
bsDateTimePicker is null

### ISSUE THREAD

**Issue by dukedave** [plusacht/ember-bootstrap-datetimepicker#6] opened 2015-01-19 21:35 UTC
I followed the readme:

```
npm install ember-bootstrap-datetimepicker --save-dev
ember g ember-bootstrap-datetimepicker
```

And put in a `{{bs-datetimepicker date=mydate format='YYYY-MM-DD'}}`.

But I get this in the JS console:

    Uncaught TypeError: undefined is not a function

Which comes from [here](https://github.com/plusacht/ember-bootstrap-datetimepicker/blob/v0.2.7/addon/components/bs-datetimepicker.js#L33), and sure enough if I put in a break point and `this.get('bsDateTimePicker')`, it's null. Any ideas?

**Comment by rafaeliga** [comment] 2015-01-20 00:36
+1

I got the same error here, @dukedave are you using ember-cli?

**Comment by dukedave** [comment] 2015-01-20 00:54
@rafaeliga yep, 0.1.5.
FWIW I've switched to https://github.com/edgycircle/ember-pikaday, which works fine.

**Comment by rafaeliga** [comment] 2015-01-20 00:56
@dukedave thanks for your tip! but I need one with time picker...

**Comment by tommyblue** [comment] 2015-01-22 11:16
I had the same problem, it's caused by the new version of bootstrap-datetimepicker.
I just opened a pull request to fix it

**Comment by claudiocro** [comment] 2015-01-22 23:09
I just released v0.2.8 where I updated to eonasdan-bootstrap-datetimepicker to 4.0.0. This should fix this error.

**Comment by rafaeliga** [comment] 2015-01-22 23:14
thanks @claudiocro !!!

**Comment by claudiocro** [comment] 2015-01-26 10:27
I'm gona close this issue. It should be fixed

**Closed by claudiocro** 2015-01-26 10:27 UTC
